name: BEDAŞ Takip

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Paketleri Kur
        run: |
          pip install -r requirements.txt

      - name: Playwright Kur
        run: |
          python -m playwright install chromium

      - name: Botu Çalıştır
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python main.py
